apiVersion: v1
kind: Service
metadata:
  name: ingestionapp
  # namespace: axion-ingestion
spec:
  type: LoadBalancer
  selector:
    app: ingestion-service
  ports:
    - port: 8000
      targetPort: 8000
  